name: main

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Say hi
      run: |
        echo hi
    - name: Secret step
      env:
        MY_SECRET: ${{ secrets.mysecret }}
      run: |
        echo $MY_SECRET > file
        cat file
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Say hi
      run: |
        echo hi
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Say hi
      run: |
        echo hi